[package]
name = "GfxBrowser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.17"
gfx_text = "0.31"
glutin = "0.12"
gfx_window_glutin = "0.20"